# This workflow will run each time a PR is opened or updated

name: CI Checks

on: push

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          cache: "yarn"
      - name: "Build"
        run: |
          yarn --frozen-lockfile --prefer-offline
          yarn build
      - name: "Build storybook"
        run: yarn build-storybook

  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          cache: "yarn"
      - name: "Install dependencies"
        run: yarn --frozen-lockfile --prefer-offline
      - name: "Run tests"
        run: yarn test

  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          cache: "yarn"
      - name: "Install dependencies"
        run: yarn --frozen-lockfile --prefer-offline
      - name: "Check types"
        run: yarn check-types

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          cache: "yarn"
      - name: "Install dependencies"
        run: yarn --frozen-lockfile --prefer-offline
      - name: "Lint"
        run: yarn lint